crab submit -c crabConfig_Data_eg_A_v1_promptreco.py
crab submit -c crabConfig_Data_eg_A_v2_promptreco.py
crab submit -c crabConfig_Data_eg_A_v3_promptreco.py
crab submit -c crabConfig_Data_eg_B_v1_promptreco.py
crab submit -c crabConfig_Data_eg_B_v2_promptreco.py
crab submit -c crabConfig_Data_eg_C_v1_promptreco.py
crab submit -c crabConfig_Data_eg_C_v2_promptreco.py
crab submit -c crabConfig_Data_eg_C_v3_promptreco.py
crab submit -c crabConfig_Data_eg_D_v2_promptreco.py
crab submit -c crabConfig_Data_jetht_A_v1_promptreco.py
crab submit -c crabConfig_Data_jetht_A_v2_promptreco.py
crab submit -c crabConfig_Data_jetht_A_v3_promptreco.py
crab submit -c crabConfig_Data_jetht_B_v1_promptreco.py
crab submit -c crabConfig_Data_jetht_B_v2_promptreco.py
crab submit -c crabConfig_Data_jetht_C_v1_promptreco.py
crab submit -c crabConfig_Data_jetht_C_v2_promptreco.py
crab submit -c crabConfig_Data_jetht_C_v3_promptreco.py
crab submit -c crabConfig_Data_jetht_D_v2_promptreco.py
crab submit -c crabConfig_Data_met_A_v1_promptreco.py
crab submit -c crabConfig_Data_met_A_v2_promptreco.py
crab submit -c crabConfig_Data_met_A_v3_promptreco.py
crab submit -c crabConfig_Data_met_B_v1_promptreco.py
crab submit -c crabConfig_Data_met_B_v2_promptreco.py
crab submit -c crabConfig_Data_met_C_v1_promptreco.py
crab submit -c crabConfig_Data_met_C_v2_promptreco.py
crab submit -c crabConfig_Data_met_C_v3_promptreco.py
crab submit -c crabConfig_Data_met_D_v2_promptreco.py
crab submit -c crabConfig_Data_sm_A_v1_promptreco.py
crab submit -c crabConfig_Data_sm_A_v2_promptreco.py
crab submit -c crabConfig_Data_sm_A_v3_promptreco.py
crab submit -c crabConfig_Data_sm_B_v1_promptreco.py
crab submit -c crabConfig_Data_sm_B_v2_promptreco.py
crab submit -c crabConfig_Data_sm_C_v1_promptreco.py
crab submit -c crabConfig_Data_sm_C_v2_promptreco.py
crab submit -c crabConfig_Data_sm_C_v3_promptreco.py
crab submit -c crabConfig_Data_sm_D_v2_promptreco.py
